name: CI Pipeline

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

