name: CI Pipeline

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Run Jest with JUnit output
      run: npx jest --ci --testResultsProcessor="jest-junit"

    - name: Upload Test Results
      if: always()  # This ensures that the artifact is uploaded even if previous steps fail
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml
